import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '~/styles/globals.css'
import { Toaster } from '~/components/ui/sonner'
import { ConvexClientProvider } from '~/providers/convex-client-provider'
import ModalProviders from '~/providers/modal-providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: [
    {
      href: '/logo.svg',
      url: '/logo.svg'
    }
  ]
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          <Toaster />
          <ModalProviders />
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  )
}
